### ISSUE TITLE
multiple user type

### ISSUE THREAD

**Issue by netwrkx** [SystangoTechnologies/Koach#1]
Hello, pls how can I support multiple user type using this system.
in the user schema, I can see default type as user. how do I add more user type to this system. thanks

**Comment by spipley-systango** [comment]
I hope I understand this correctly and you are talking about just the user type and not different roles.
As far as user types are concerned, you can just enter different values during user creation [the sign-up API](https://github.com/SystangoTechnologies/Koach/blob/master/src/modules/users/controller.js#L41). You would need to handle this in your APIs.

**Comment by netwrkx** [comment]
okay, then how do I handle different user roles during signup

**Comment by spipley-systango** [comment]
Hello, so for setting different roles you can pass it into body for user signup API call (https://github.com/SystangoTechnologies/Koach/blob/master/src/modules/users/router.js#L11).

Or you can decide your user role on the basis of you body data in the user controller (https://github.com/SystangoTechnologies/Koach/blob/master/src/modules/users/controller.js#L41).
